// Generated-web-asset embedder.
//
//     swift tools/embed-web.swift web Sources/PhotoCleaner/Web/GeneratedWebAssets.swift
//
// The UI lives as ordinary editable files under `web/`, and the build folds them
// into the executable as raw Swift string literals. That keeps the runtime
// dependency-free (no bundle to locate, no path that could be traversed) while
// leaving the HTML/CSS/JS reviewable and diffable in the repository.

import Foundation

func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data("embed-web: \(message)\n".utf8))
    exit(1)
}

let arguments = CommandLine.arguments
guard arguments.count == 3 else {
    fail("usage: embed-web <source-directory> <output-file>")
}

let sourceDirectory = URL(fileURLWithPath: arguments[1])
let outputPath = arguments[2]

struct Asset {
    let file: String
    let symbol: String
}

let assets = [
    Asset(file: "index.html", symbol: "indexHTML"),
    Asset(file: "app.css", symbol: "appCSS"),
    Asset(file: "app.js", symbol: "appJS"),
]

// A new file added to web/ but not listed above would compile and run happily
// while never being served — the worst kind of silent shipping failure. Catch
// it here instead.
let embeddableExtensions: Set<String> = ["html", "css", "js"]
if let entries = try? FileManager.default.contentsOfDirectory(atPath: sourceDirectory.path) {
    let embedded = Set(assets.map(\.file))
    let orphans = entries
        .filter { embeddableExtensions.contains(URL(fileURLWithPath: $0).pathExtension.lowercased()) }
        .filter { !embedded.contains($0) }
        .sorted()
    if !orphans.isEmpty {
        fail("web/ contains files that are not embedded: \(orphans.joined(separator: ", ")). Add them to the asset list and give them a symbol.")
    }
}

// In an extended-delimiter raw string (`#"""…"""#`) only this exact byte
// sequence terminates the literal, so any content containing it must be caught
// here rather than producing a file that will not compile.
let terminator = "\"\"\"#"

var rendered = """
// Generated by tools/embed-web.swift from web/ — do not edit by hand.
// Edit the files in web/ and rebuild.

import Foundation

enum EmbeddedWebAssets {

"""

for asset in assets {
    let url = sourceDirectory.appendingPathComponent(asset.file)
    guard let data = try? Data(contentsOf: url) else {
        fail("cannot read \(url.path)")
    }
    guard var text = String(data: data, encoding: .utf8) else {
        fail("\(asset.file) is not valid UTF-8")
    }
    guard !text.contains(terminator) else {
        fail("\(asset.file) contains the raw-string terminator \(terminator)")
    }
    if !text.hasSuffix("\n") { text += "\n" }

    rendered += "    static let \(asset.symbol) = #\"\"\"\n"
    rendered += text
    rendered += "\"\"\"#\n\n"
}

rendered += """
    static func bytes(named name: String) -> Data? {
        switch name {
        case "index.html": return Data(indexHTML.utf8)
        case "app.css": return Data(appCSS.utf8)
        case "app.js": return Data(appJS.utf8)
        default: return nil
        }
    }
}

"""

do {
    try rendered.write(toFile: outputPath, atomically: true, encoding: .utf8)
} catch {
    fail("cannot write \(outputPath): \(error.localizedDescription)")
}

let total = assets.reduce(0) { partial, asset in
    partial + ((try? Data(contentsOf: sourceDirectory.appendingPathComponent(asset.file)))?.count ?? 0)
}
print("embed-web: embedded \(assets.count) assets (\(total) bytes) into \(outputPath)")
